name: TER release

on:
  push:
    tags:
      - '*'

jobs:
  ter-release:
    name: TER release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl, mbstring, xml, soap, zip, curl

      - name: Install EXT:tailor
        run: composer global require typo3/tailor "^1.0" --prefer-dist --no-progress --no-suggest

      - name: Some output
        run: echo "The extension is $EXTENSION_KEY"

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload EXT:${{ env.EXTENSION_KEY }} as ${{ steps.get_version.outputs.VERSION }} to TER
        run: php ~/.composer/vendor/bin/tailor ter:publish ${{ steps.get_version.outputs.VERSION }} --path=./$TYPO3_EXTENSION_KEY --comment="New release ${{ steps.get_version.outputs.VERSION }}. See details, changelog and documentation on https://github.com/$GITHUB_REPOSITORY"
